# Generated by Django 4.2.2 on 2023-08-24 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userrelation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRelation',
        ),
    ]
